import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: 'http://localhost:8000/api/graphql',
  documents: [
    '../../apps/frontend/**/graphql/**/*.graphql',
    '../../apps/admin/**/graphql/**/*.graphql',
    '../../apps/common/**/graphql/**/*.graphql',
  ],
  hooks: {
    afterAllFileWrite: ['prettier --write'],
  },
  generates: {
    'generated/index.tsx': {
      config: {
        withHooks: true,
        withComponent: false,
        withHOC: false,
      },
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-urql',
        {
          add: {
            content: `
            /* eslint-disable */
            // @ts-ignore
            // DO NOT EDIT
            // This file is automatically generated, run pnpm gen to update
            `,
          },
        },
      ],
    },
  },
};
export default config;
